export const PROMPTS = [
  'What is one moment from today you want to remember?',
  'What made you smile today?',
  'What is one challenge you faced today, and how did you handle it?',
  'What are you grateful for right now?',
  'Describe a small win you had today.',
  'What did you learn today?',
  'Who made your day better, and why?',
  'What is one thing you did for yourself today?',
  'What is something you want to let go of?',
  'What energized you today?',
  'What drained your energy today?',
  'Describe a conversation that stood out today.',
  'What is one intention you want to set for tomorrow?',
  'What is something you would do differently today?',
  'What is a memory you replayed today?',
  'What is a sound, smell, or sight you noticed today?',
  'What is one act of kindness you witnessed or did?',
  'What is one thing you are proud of today?',
  'What is a worry you can release tonight?',
  'What is one place you visited or wish you visited today?',
  'What is one thing you want to improve this week?',
  'What is a boundary you honored today?',
  'What is a habit you are building right now?',
  'What is one thing you are looking forward to?',
  'What is a risk you took today, big or small?',
  'What is something you avoided today, and why?',
  'What is one thing you appreciated about your body today?',
  'What is one thing you noticed about your mood today?',
  'What is a task you completed that mattered?',
  'What is one thing you can simplify tomorrow?',
  'What is something you want to remember about today?',
  'What was the highlight of your day?',
  'What was the hardest part of your day?',
  'What is one step you took toward a goal today?',
  'What is one thing you want to celebrate tonight?',
  'What is a new idea you had today?',
  'What is a moment of calm you experienced today?',
  'What is a moment of courage you showed today?',
  'What is something you wish you said today?',
  'What is a small detail you do not want to forget?',
  'What is one thing you did that aligned with your values?',
  'What is a distraction you can reduce tomorrow?',
  'What is one thing you did well today?',
  'What is one thing you want to ask for help with?',
  'What is a goal you are working toward this month?',
  'What is one way you nurtured a relationship today?',
  'What is something you are curious about right now?',
  'What is one thing you want to forgive yourself for?',
  'What is one thing you want to carry forward from today?',
  'What is one thing you want to leave behind from today?',
];
